apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"details","service":"details"},"name":"details","namespace":"default"},"spec":{"ports":[{"name":"http","port":9080}],"selector":{"app":"details"}}}
  creationTimestamp: "2023-08-25T21:15:40Z"
  labels:
    app: details
    service: details
  name: details
  namespace: default
  resourceVersion: "28797"
  uid: bedc5e0c-9015-4ce5-a4b8-72395d2660b1
spec:
  clusterIP: 10.110.9.125
  clusterIPs:
  - 10.110.9.125
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: details
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
