apiVersion: v1
data:
  alertmanager.yml: |
    route:
      group_by: ['job']
      repeat_interval: 30m
      group_interval: 5m
      receiver: 'null'
    receivers:
    - name: 'null'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"alertmanager.yml":"route:\n  group_by: ['job']\n  repeat_interval: 30m\n  group_interval: 5m\n  receiver: 'null'\nreceivers:\n- name: 'null'\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"alertmanager-config","namespace":"monitoring"}}
  creationTimestamp: "2023-08-26T16:53:40Z"
  name: alertmanager-config
  namespace: monitoring
  resourceVersion: "116024"
  uid: 3879e96a-fdb4-4530-a5c2-a094b85bf1ed
